apiVersion: v1
kind: ConfigMap
metadata:
  name: download-csd
  namespace: default
data:
  download-csd.sh: |
    cd /data
    wget --no-check-certificate -E -k -p https://csd.uoc.gr
    if [ $? -eq 0 ]; then
      echo "sucess"
    else
      echo "failed"
      exit 1
    fi
    if [ -d /data/csd.uoc.gr ]; then
      echo "sucess"
    else
      echo "failed"
    fi
    ls -la /data/csd.uoc.gr
---
apiVersion: batch/v1
kind: Job
metadata:
  name: download-csd
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: download-csd
        image: ubuntu:24.04
        command: ["/bin/bash", "-c"]
        args:
          - |
            export DEBIAN_FRONTEND=noninteractive
            apt-get update && apt-get install -y --no-install-recommends wget ca-certificates &&
            exec /bin/bash /scripts/download-csd.sh
        volumeMounts:
        - name: script-volume
          mountPath: /scripts
        - name: data-volume
          mountPath: /data
      volumes:
      - name: script-volume
        configMap:
          name: download-csd
          defaultMode: 0755
      - name: data-volume
        emptyDir: {}
      restartPolicy: Never
  backoffLimit: 1