---
apiVersion: v1
kind: Namespace
metadata:
  name: greetings-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: greeting-controller
  namespace: greetings-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: greeting-controller
rules:
  - apiGroups: ["hy548.csd.uoc.gr"]
    resources: ["greetings"]
    verbs: ["get", "list", "watch", "patch", "update"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: greeting-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: greeting-controller
subjects:
  - kind: ServiceAccount
    name: greeting-controller
    namespace: greetings-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeting-controller
  namespace: greetings-system
  labels:
    app: greeting-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greeting-controller
  template:
    metadata:
      labels:
        app: greeting-controller
    spec:
      serviceAccountName: greeting-controller
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: controller
          image: panpas161/assignment4-ex2:latest
          imagePullPolicy: Always
          env:
            - name: TMPDIR
              value: /tmp
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: kopf-home
              mountPath: /home/kopf
      volumes:
        - name: tmp
          emptyDir: {}
        - name: kopf-home
          emptyDir: {}
