apiVersion: v1
kind: Namespace
metadata:
  name: custom-label-injector
  labels:
    app: custom-label-injector
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: issuer-selfsigned
  namespace: custom-label-injector
  labels:
    app: custom-label-injector
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: controller-certificate
  namespace: custom-label-injector
  labels:
    app: custom-label-injector
spec:
  secretName: controller-certificate
  duration: 87600h
  commonName: controller.custom-label-injector.svc
  dnsNames:
  - controller.custom-label-injector.svc
  privateKey:
    algorithm: RSA
    size: 2048
  issuerRef:
    name: issuer-selfsigned
---
apiVersion: v1
kind: Service
metadata:
  name: controller
  namespace: custom-label-injector
  labels:
    app: custom-label-injector
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: https
      name: https
  selector:
    app: custom-label-injector
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
  namespace: custom-label-injector
  labels:
    app: custom-label-injector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom-label-injector
  template:
    metadata:
      labels:
        app: custom-label-injector
    spec:
      containers:
      - name: webhook
        image: docker.io/panpas161/assignment4-ex3:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 443
          name: https
        env:
        - name: PORT
          value: "443"
        - name: TLS_CERT_FILE
          value: /etc/ssl/keys/tls.crt
        - name: TLS_KEY_FILE
          value: /etc/ssl/keys/tls.key
        volumeMounts:
        - name: controller-certificate-volume
          mountPath: /etc/ssl/keys
          readOnly: true
        readinessProbe:
          tcpSocket:
            port: https
          initialDelaySeconds: 3
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: https
          initialDelaySeconds: 10
          periodSeconds: 10
      volumes:
      - name: controller-certificate-volume
        secret:
          secretName: controller-certificate
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: custom-label-injector
  namespace: custom-label-injector
  labels:
    app: custom-label-injector
  annotations:
    cert-manager.io/inject-ca-from: custom-label-injector/controller-certificate
webhooks:
  - name: controller.custom-label-injector.svc
    clientConfig:
      service:
        name: controller
        namespace: custom-label-injector
        path: "/mutate"
    rules:
      - operations: ["CREATE"]
        apiGroups: ["*"]
        apiVersions: ["*"]
        resources: ["pods", "deployments"]
    namespaceSelector:
      matchLabels:
        custom-label-injector: enabled
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None
    failurePolicy: Fail
